import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "NEXT EXERCISR",
  description: "Generated by create next app",
};

const turkishAirlines = localFont({
  src: [
    {
      path: '../app/fonts/turkishairlines.woff2',
      weight: '400',
      style: 'normal',
    },
 {
      path: '../app/fonts/turkishairlinesbold.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-turkishairlines',
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" className={turkishAirlines.variable}>
      <body className={`${turkishAirlines.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
